configs:
  openhim-console-conf:
    file: ./infrastructure/openhim-console-config.deploy.json
  traefik:
    file: ./infrastructure/traefik.toml
  hearth-check-dupe-plugin:
    file: ./infrastructure/hearth-plugins/checkDuplicateTask.js
  hearth-queryparam-extensions-conf:
    file: ./infrastructure/hearth-queryparam-extensions.json
  netdata-master-stream:
    file: ./infrastructure/netdata-master-stream.conf
  netdata-slave:
    file: ./infrastructure/netdata-slave.conf
  netdata-slave-stream:
    file: ./infrastructure/netdata-slave-stream.conf
