# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  # Configure mongo nodes as a replica set
  mongo1:
    image: mongo:3.6
    restart: unless-stopped
    command: --replSet rs0
    volumes:
      - './data/mongo1:/data/db'
    deploy:
      replicas: 1
    networks:
      - overlay_net

  mongo2:
    image: mongo:3.6
    restart: unless-stopped
    command: --replSet rs0
    volumes:
      - './data/mongo2:/data/db'
    deploy:
      replicas: 1
    networks:
      - overlay_net

  mongo3:
    image: mongo:3.6
    restart: unless-stopped
    command: --replSet rs0
    volumes:
      - './data/mongo3:/data/db'
    deploy:
      replicas: 1
    networks:
      - overlay_net

  mongo-rs-init:
    image: mongo:3.6
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: bash -c 'sleep 20; mongo --host mongo1 --eval "rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongo1:27017\"},{_id:1,host:\"mongo2:27017\"},{_id:2,host:\"mongo3:27017\"}]})"'
    deploy:
      restart_policy:
        condition: none
    networks:
      - overlay_net

  # Configure redis
  redis:
    image: redis:5
    restart: unless-stopped
    networks:
      - overlay_net

  # Configure elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    restart: unless-stopped
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'
      - './data/backups/elasticsearch:/data/backups/elasticsearch'
      - './infrastructure/elasticsearch/elasticsearch.yml:/config/elasticsearch.yml'
      - './infrastructure/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.data-elasticsearch == true
    networks:
      - overlay_net

  # Configure influxdb
  influxdb:
    image: mongo:3.6
    restart: unless-stopped
    volumes:
      - './data/influxdb:/var/lib/influxdb'
      - './data/backups/influxdb:/data/backups/influxdb'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.data-elasticsearch == true
    networks:
      - overlay_net

networks:
  overlay_net:
    external:
      name: opencrvs
