version: '3.3'

services:
  # Configure other dependencies with deployment specifc details
  hearth:
    image: jembi/hearth:v1.0.0-beta.1
    environment:
      - mongodb__url=mongodb://mongo1,mongo2,mongo3/hearth-dev?replicaSet=rs0
      - logger__level=error
      - authentication__type=disabled
      - idGenerator=uuidv4
      - server__fhirVersion=stu3
    deploy:
      replicas: 2
    secrets:
      - jwt-public-key
    configs:
      - source: hearth-check-dupe-plugin
        target: /src/hearth/lib/plugins/checkDuplicateTask.js
      - source: hearth-queryparam-extensions-conf
        target: /src/hearth/config/queryparam-extensions.json
    networks:
      - overlay_net

  openhim-core:
    image: jembi/openhim-core:5
    environment:
      - mongo_url=mongodb://mongo1,mongo2,mongo3/openhim-dev?replicaSet=rs0
      - mongo_atnaUrl=mongodb://mongo1,mongo2,mongo3/openhim-dev?replicaSet=rs0
      - logger_level=error
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=opencrvs_overlay_net'
        - 'traefik.openhim-api.frontend.rule=Host: openhim-api.${HOSTNAME}'
        - 'traefik.openhim-api.protocol=https'
        - 'traefik.openhim-api.port=8080'
        - 'traefik.router.frontend.rule=Host: api.${HOSTNAME}'
        - 'traefik.router.port=5001'
      replicas: 2
    networks:
      - overlay_net

  openhim-console:
    image: jembi/openhim-console:1.13
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: openhim.${HOSTNAME}'
        - 'traefik.port=80'
        - 'traefik.docker.network=opencrvs_overlay_net'
      replicas: 2
    configs:
      - source: openhim-console-conf
        target: /usr/share/nginx/html/config/default.json
    networks:
      - overlay_net

  logspout:
    image: gliderlabs/logspout:latest
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog://${PAPERTRAIL:-logs5.papertrailapp.com:24584}
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    networks:
      - overlay_net

secrets:
  jwt-public-key:
    external: true

configs:
  openhim-console-conf:
    file: ./infrastructure/openhim-console-config.deploy.json
  hearth-check-dupe-plugin:
    file: ./infrastructure/hearth-plugins/checkDuplicateTask.js
  hearth-queryparam-extensions-conf:
    file: ./infrastructure/hearth-queryparam-extensions.json

networks:
  overlay_net:
    external:
      name: opencrvs
