# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

# This is used so we can comunicate with OpenHIM's API while it uses
# the default self-signed cert. This makes configuration easier and
# is ok because all communication takes place on a private docker
# swarm network.
insecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]

[api]

[ping]

[docker]
domain = "draman.iprocuratio.com"
swarmMode = true
exposedByDefault = false
watch = true

[acme]
email = "afoone@hotmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
  main = "draman.iprocuratio.com"
  sans = [
    "register.draman.iprocuratio.com",
    "login.draman.iprocuratio.com",
    "auth.draman.iprocuratio.com",
    "gateway.draman.iprocuratio.com",
    "resources.draman.iprocuratio.com",
    "openhim-api.draman.iprocuratio.com",
    "api.draman.iprocuratio.com",
    "openhim.draman.iprocuratio.com",
    "webhooks.draman.iprocuratio.com",
  ]

[retry]

# Enable gzip compression
[http.middlewares]
  [http.middlewares.test-compress.compress]
